export default {
  HOME_STACK: 'HOME_STACK',
  HOME_SCREEN: 'HOME_SCREEN',
  ORDER_SCREEN: 'ORDER_SCREEN',
  PRODUCT_INFO: 'PRODUCT_INFO',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  HOME_TAB: 'HOME_TAB',
  CART_SCREEN: 'CART_SCREEN',
  CHECKOUT: 'CHECKOUT',
  ORDER_STACK: 'ORDER_STACK',
  ROOT_STACK: 'ROOT_STACK',
  ORDER_DETAILS: 'ORDER_DETAILS',
};
