export default Strings = {
  appName: 'Ragazon',
  success: 'success',
  pending: 'pending',
  idle: 'idle',
  failed: 'failed',
  error: 'Error',
  YupErrors: {
    requireEmailError: 'Email is required field!!',
    invalidEmailError: 'Email is invalid!!',
    requirePasswordError: 'Password is required field!!',
    lengthPasswordError: 'Password length must be atleast 8!!',
    lowercasePasswordError:
      'Password must have atleast 1 lowercase character!!',
    upperCasePasswordError:
      'Password must have atleast 1 uppercase character!!',
    specialCasePasswordError:
      'Password must have atleast 1 special character!!',
    digitPasswordError: 'Password must have atleast 1 digit!!',
    requireConfirmPasswordError: 'Confirm password is required field!!',
    passwordNotMatchError: 'Passwords do not match!!',
    requireUserNameError: 'Username is required field!!',
    requireFNameError: 'First Name is required field!!',
    requireLNameError: 'Last Name is required field!!',
    requirePhoneError: 'Phone is required field!!',
    invalidPhoneError: 'Phone number is invalid!!',
    requireCountryError: 'Country is required field!!',
    requireCityError: 'City is required field!!',
    requireStateError: 'State is required field!!',
    requireAddressError: 'Address is required field',
    onlyAlphabetsError: 'Only Alphabets allowed!!',
  },
  Placeholders: {
    search: 'Search the product..',
    enterEmail: 'Enter email',
    enterPassword: 'Enter password',
    confirmPassword: 'Confirm password',
    enterFirstName: 'Enter first name',
  },
  GeneralErrors: {
    emailAlreadyTaken: 'Email already taken. Please try again',
    invalidCredentials: 'Invalid credentials',
    pleaseTryAgain: 'Please try again',
  },
  headerTitles: {
    home: 'Home',
    orders: 'Orders',
    orderDetails: 'Order Details',
    cart: 'Cart',
    checkout: 'Checkout',
    productDetails: 'Product Details',
  },
  buttonTitles: {
    addToCart: 'Add to cart',
    removeFromCart: 'Remove from cart',
    checkout: 'Checkout',
    register: 'Register',
    loginWithAccount: 'Login with your account',
    createYourAccount: 'Create your account',
  },
  deleteProductConfirmation: 'Do you want to delete the product?',
  logOutConfirmation: 'Are you sure you want to log out?',
  thanksMessage: 'Thank you for purchasing',
  orderConfirmationMessage: 'Your order will be placed in 2-3 working days!!',
  alreadyHaveAccount: 'Already have an account',
  newToApp: 'New to Ragazon?',
};
