export default Strings = {
  FieldError: {
    country: 'This Field is Required',
    fullName: 'This Field is Required',
    number: 'This Field is Required',
    pincode: 'This Field is Required',
    landmark: 'This Field is Required',
    address: 'This Field is Required',
    city: 'This Field is Required',
    state: 'This Field is Required',
    email: 'This Field is Required',
    password: 'This Field is Required',
    username: 'This Field is Required',
    loginPassword: 'This Field is Required',
  },
  MinCharError: {
    country: 'minimum 2 character are required',
    fullName: 'minimum 5 character are required',
    number: 'minimum 10 character are required',
    pincode: 'minimum 6 character are required',
    landmark: 'minimum 5 character are required',
    address: 'minimum 10 character are required',
    city: 'minimum 2 character are required',
    state: 'minimum 2 character are required',
    email: 'minimum 10 character are required',
    password: 'minimum 8 character are required',
    username: 'minimum 2 character are required',
  },
  MaxCharError: {
    country: 'maximum 15 character are used',
    fullName: 'maximum 20 character are used',
    number: 'maximum 10 character are used',
    pincode: 'maximum 6 character are used',
    landmark: 'maximum 11 character are used',
    address: 'maximum 40 character are used',
    city: 'maximum 15 character are used',
    state: 'maximum 15 character are used',
    email: 'maximum 30 character are used',
    password: 'maximum 15 character are used',
    username: 'maximum 25 character are used',
  },
};
